### ISSUE TITLE
JSON Error

### ISSUE THREAD

**Issue by EinfachRuwen** [maubot/disruptor#6]
I have the problem:
```
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://www.reddit.com/r/catpictures/.json?raw_json=1')
```
What can I do?

**Comment by tulir** [comment]
Reddit's API is still broken (it returns 429 immediately), but now the bot also supports getting images from source.unsplash.com (and it's easier to add more sources)
