### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by jahway603** [maubot/disruptor#8]
The last release of this plugin was from 2019. Can you please release a new version as many bugfixes appear to have been applied after the last release?

**Comment by ikkemaniac** [comment]
you could just 'build' it yourself. Download a copy of this archive/clone and build it:
https://docs.mau.fi/maubot/usage/cli/build.html

**Comment by jahway603** [comment]
@ikkemaniac I would love to do that, but I'm having an issue with mbc not working as I've [documented here](https://gist.github.com/jahway603/1067d05c3d6e6fcf3b4f1ba3f63fe1a7). Not clear if the Arch AUR package is messed up or mbc is not working for another reason. Since I am currently not able to build it myself, as I'd prefer, I opened this issue to get a new release created.

**Comment by ikkemaniac** [comment]
those errors complain about missing dependencies. fix that by rerunning pip to reinstall maubot and again to install plugin requirements.

for building the plugin you can also:
> With the maubot.yaml meta file above and this Python file saved as examplebot/__init__.py, you can build the plugin and try it out. To build plugins, you can either use mbc build or just zip it yourself (zip -9r plugin.mbp * in the directory with maubot.yaml). After you have the .mbp file, upload it to your maubot instance (see [Basic usage](https://docs.mau.fi/maubot/usage/basic.html)), then try to use the !hello-world command.

https://docs.mau.fi/maubot/dev/getting-started.html?highlight=zip#getting-started

**Comment by jahway603** [comment]
Thank you for your help @ikkemaniac. I was able to get `mbc build` working and build this.
